load: ${reward_load}
load_iteration: ${reward_load_iteration}
num_layers: ${reward_num_layers}
hidden_size: ${reward_hidden_size}
num_attention_heads: ${reward_num_attention_heads}
use_distributed_optimizer: True
tensor_model_parallel_size: ${reward_tp}
pipeline_model_parallel_size: 1
seq_length: ${max_seq_len}
max_position_embeddings: ${max_seq_len}


save_inference: False
save_inference_interval: 100000