includes:
  - base_train.yaml
  - reward_shared.yaml

pipeline_model_parallel_size: ${ppo_value_pp:1}
lr_decay_iters: 12000
lr_warmup_iters: 100
lr: ${value_lr:5e-6}
min_lr: ${value_min_lr:5e-7}
lr_decay_style: ${value_lr_decay_style:linear}
weight_decay: 0.01
log_interval: 1

use_checkpoint_opt_param_scheduler: False
adam_beta1: 0.9
adam_beta2: 0.95
num_workers: 8
init_method_std: 0.006

recompute_granularity: selective

no_load_optim: True
no_load_rng: True
no_load_args: True
no_load_scheduler: True
sequence_parallel: True

recompute_activations: ${value_recompute_activations:False}
recompute_granularity: ${value_recompute_granularity:None}
moe_layer_recompute: ${value_moe_layer_recompute:False}
