load: ${reward_load}
load_iteration: ${reward_load_iteration}
# enable use_distributed_optimizer will raise error for reward/value, disable temply
use_distributed_optimizer: False

num_layers: ${reward_num_layers}
hidden_size: ${reward_hidden_size}
num_attention_heads: ${reward_num_attention_heads}
ffn_hidden_size: ${reward_ffn_hidden_size}
tensor_model_parallel_size: ${reward_tp:8}
num_query_groups: ${reward_num_query_groups}

save_inference: True
save_inference_interval: 10